### ISSUE TITLE
Problema en el comando "roulette"

### ISSUE THREAD

**Issue by Cardinalx6** [Mateo-tem/COSM0#1]
Al utilizar el comando roulette, no importa por qué color apuestes entre black o red, siempre vas a perder, aunque la apuesta salga en el color que elegiste aún así dice que perdiste y te quita dinero, esto perjudica a los usuarios ya que pueden perder mucho dinero. Saludos.

**Comment by Mateo-tem** [comment]
Reparado. Lo que pasó fue de que al sacar el resultado aleatorio, no era igual, ya que Uno estaba en mayúsculas y otro en minúsculas. Ejemplo: Lo que tu pusiste es "red", pero el resultado aleatorio que sacaba el bot era "Red". Como ves, son diferentes, pero ya lo arreglé, Gracias por reportar el error.
