### ISSUE TITLE
Bug en el comando: warn

### ISSUE THREAD

**Issue by polarsito** [Mateo-tem/COSM0#10]
![image](https://user-images.githubusercontent.com/91166604/147521350-a9bb98dd-7be5-4a6a-a7b0-59f3a77af172.png)
No se si se considera un bug, pero al warnear por primera vez tira el mensaje de aviso que espere que se cargue la data y intente otra vez, el tema es que si reviso sus warns figura un tiempo bugeado. (Digo que quizas no se considera debido a su mensaje de advertencia y que al advertir otra vez eso se arregla, en caso de no considerarse un bug, por favor cerrar esta issue)

**Comment by Mateo-tem** [comment]
Arreglado. El bug se produjo porque la propiedad "time" no estaba definida en la base de datos al guardar por primera vez los datos. Ya se añadió. Gracias por reportar el error. Saludos. Si aún le aparece lo mismo, es porque la base de datos está ya con esos datos, mientras no lo warnees, no desaparecerá.
