### ISSUE TITLE
El comando daily debería funcionar cada 24h

### ISSUE THREAD

**Issue by drgatoxd** [Mateo-tem/COSM0#11]
El comando daily tiene un cooldown de 12 horas

![Screenshot_20211229-125046_Discord](https://user-images.githubusercontent.com/43690887/147690042-f8f2441b-bd90-4e31-a9c9-bd796252613e.jpg)

**Comment by Mateo-tem** [comment]
Arreglado, de 12 horas ha sido modificado a 24h. Cada 24h el usuario podrá reclamar su Recompensa Diaria.
