### ISSUE TITLE
El botón de crear ticket no funciona

### ISSUE THREAD

**Issue by drgatoxd** [Mateo-tem/COSM0#12]
Cuando le doy al botón de crear ticket, el bot no reacciona y retorna interacción fallida
![image](https://user-images.githubusercontent.com/43690887/147716756-d17c2461-c8cc-46d0-8091-b6cbeea50ad2.png)

En la siguiente imagen se muestra que el bot tiene permisos de administrador
![image](https://user-images.githubusercontent.com/43690887/147716803-49b23c24-7a2a-42c2-b623-3b7aa7ee77e9.png)

**Comment by Mateo-tem** [comment]
¿Sigue dando lo mismo? Yo lo apagué porque le estaba haciendo mantenimiento.

**Comment by drgatoxd** [comment]
si xd
![image](https://user-images.githubusercontent.com/43690887/147719573-ae697432-be62-415c-bcd1-a72e987f14e0.png)

**Comment by Mateo-tem** [comment]
¿Me pasas la ID de tu servidor, por favor? Esto es porque quiero comprobar algo en la base de datos.

**Comment by drgatoxd** [comment]
> ¿Me pasas la ID de tu servidor, por favor? Esto es porque quiero comprobar algo en la base de datos.

Esa es la ID: 912152924422037574

**Comment by Mateo-tem** [comment]
Y si lo estableces de nuevo?

**Comment by Mateo-tem** [comment]
Ah, perdón lo cerré sin querer

**Comment by drgatoxd** [comment]
Sigue sin funcionar
![Screenshot_20211231-134548_Discord.jpg](https://user-images.githubusercontent.com/43690887/147835997-3c405dab-6ffa-4fd9-b6cb-82364578d0c9.jpg)

**Comment by Mateo-tem** [comment]
Me puedes enviar 2 cosas?
- La ID del canal
- La ID del Mensaje

**Comment by drgatoxd** [comment]
- Mensaje: 926623485705465896
- Canal: 918969588442624082

**Comment by andleo17** [comment]
¡Muchas gracias por tu aportación a Cosmo!
Te comentamos que ya está arreglado el bug. Pronto estaremos implementando la actualización.
