### ISSUE TITLE
Bug el comando denysug

### ISSUE THREAD

**Issue by drgatoxd** [Mateo-tem/COSM0#13]
Cuando creo un embed con color `#ED4245` y uso `c!denysug` poniendo la ID de ese embed sale el mensaje `The suggestion is already approved or denied.` 

![image](https://user-images.githubusercontent.com/43690887/147717887-283a3af9-9bd9-4833-8161-5fb87f9111e7.png)

**Comment by Mateo-tem** [comment]
Arreglado. Gracias por reportar el error.
