### ISSUE TITLE
Bug al usar timeout con el propietario del servidor

### ISSUE THREAD

**Issue by drgatoxd** [Mateo-tem/COSM0#14]
Si uso `c!timeout` con el propietario del servidor el bot no responde
![image](https://user-images.githubusercontent.com/43690887/147718185-faef89b9-b9ba-417b-90cb-a576588aada8.png)
![image](https://user-images.githubusercontent.com/43690887/147718281-2082eafa-a0e9-4f66-b2ec-98d6463f0170.png)

*el owner no tenía ningún rol*

**Comment by Mateo-tem** [comment]
Arreglado. Sí, el bot lanzaba un error ya que ese miembro (owner) tiene más prioridad que el mismo bot. Gracias por reportarlo. Saludos.
