### ISSUE TITLE
Error en comando /search

### ISSUE THREAD

**Issue by drgatoxd** [Mateo-tem/COSM0#15]
Cuando busco una canción de Spotify en la búsqueda sale interacción fallida
![image](https://user-images.githubusercontent.com/43690887/147720289-235b02e6-3ec6-463f-9478-34d46e0751d3.png)

*se puede poner al menos un mensaje de error xd*

**Comment by Mateo-tem** [comment]
Creo que ya está solucionado. Si volviera a pasar, puedes volver a abrir el Issue. Gracias y saludos.
