### ISSUE TITLE
comando userinfo no responde

### ISSUE THREAD

**Issue by drgatoxd** [Mateo-tem/COSM0#16]
Al intentar usar el comando `c!userinfo` el bot no responde. Probé mencionando a un usuario al usar el comando y aún así no respondió.
![image](https://user-images.githubusercontent.com/43690887/147841696-30920c4e-1c38-40ad-b639-d45b54b1704e.png)

**Comment by Mateo-tem** [comment]
De hecho, ese comando estuvo en mantenimiento justo en el momento que lo usaste. Trata de probarlo de nuevo y me avisas si no responde o sí.

**Comment by drgatoxd** [comment]
El comando ya funciona
![Screenshot_20211231-232623_Discord.jpg](https://user-images.githubusercontent.com/43690887/147843979-ed4e429e-6f7a-4462-9eee-2769ef48be46.jpg)
