### ISSUE TITLE
No se puede usar los items en economía

### ISSUE THREAD

**Issue by SamuelTN** [Mateo-tem/COSM0#17]
![No](https://user-images.githubusercontent.com/97559088/149571363-2bf8e7d2-d7c1-47f2-bc84-13a1e9d04c5e.png)

**Comment by andleo17** [comment]
Gracias por reportar este bug.
Por favor necesito que me des los siguientes datos:

- Tu ID de usuario

**Comment by SamuelTN** [comment]
774443686091030568

**Comment by Mateo-tem** [comment]
Ya hemos arreglado este error. En la próxima actualización ya estará arreglado. ¡Gracias!

**Comment by Mateo-tem** [comment]
No se podía usar, porque tal vez pusiste un item que no se puede usar. Por ejemplo un rol y así, pero trataremos de arreglarlo de todas maneras.
