### ISSUE TITLE
Bug de COSM0

### ISSUE THREAD

**Issue by Drago285** [Mateo-tem/COSM0#2]
en la ruleta yo aposte por el color rojo y el bot dice que perdi dice que callo en rojo y yo aposte al rojo

**Comment by Mateo-tem** [comment]
Reparado. Lo que pasó fue de que al sacar el resultado aleatorio, no era igual, ya que uno estaba en mayúsculas y otro en minúsculas. Ejemplo: Lo que tu pusiste es "red", pero el resultado aleatorio que sacaba el bot era "Red". Como ves, son diferentes, pero ya lo arreglé, Gracias por reportar el error.
