### ISSUE TITLE
Bug con el comando para detectar usuarios maliciosos

### ISSUE THREAD

**Issue by Drago285** [Mateo-tem/COSM0#3]
Invite al bot a un server de pruebas en donde estoy yo y Mee6 y un bot que estoy creando y dice que encontro usuarios maliciosos

**Comment by ddiablou** [comment]
Y... hace cuanto creaste "ese bot"?

**Comment by Drago285** [comment]
Hace como un mes, pero lo sigo haciendo

**Comment by Mateo-tem** [comment]
Arreglado. Lo que pasó fue de que el título y descripción del Embed estaban mal configurados, ahora ya están reparados. Gracias por reportar el error. Saludos.
