### ISSUE TITLE
Bug con el comando de agregar emojis

### ISSUE THREAD

**Issue by Drago285** [Mateo-tem/COSM0#5]
Uso el comando para agregar emojis al servidor y no funciona

**Comment by Mateo-tem** [comment]
¿Podrías mandar una captura de lo sucedido? Gracias.

**Comment by Mateo-tem** [comment]
Ya arreglé todos los bugs que podría haber con ese comando. Sobre todo el de que el bot no responde cuando son emojis predeterminados de Discord. Gracias por reportarlo. Saludos
