### ISSUE TITLE
Puedo depositar valor Infinito, y también retirarlo, y también pagar, basicamente Infinity se considera número

### ISSUE THREAD

**Issue by polarsito** [Mateo-tem/COSM0#6]
Prueba 1: https://imgur.com/NvGj2Eq
Prueba 2: https://imgur.com/pKEGRKF
Prueba 3 -> pay: https://imgur.com/undefined

**Comment by Mateo-tem** [comment]
Reparado. Sí, es cierto, "Infinity" es un número. Gracias por reportar el error. ¡Saludos!
