### ISSUE TITLE
Bug en un collector.

### ISSUE THREAD

**Issue by polarsito** [Mateo-tem/COSM0#7]
![image](https://user-images.githubusercontent.com/91166604/147520646-93524819-6a42-4cc9-853e-506b4455d965.png)

No sé si ustedes lo consideran un bug, pero cuando acaba el tiempo del collector, al querer usar el menu de categorías tira Interacción Fallida. Se puede evitar usando el evento end de un collector y deshabilitar el menu <.>

**Comment by Mateo-tem** [comment]
No era considerado un bug, pero para evitar confusiones, editamos el mensaje para avisar que se le acabó el tiempo. Gracias por reportarlo. Saludos.
