### ISSUE TITLE
Bug en el comando de barra: volume

### ISSUE THREAD

**Issue by polarsito** [Mateo-tem/COSM0#8]
![image](https://user-images.githubusercontent.com/91166604/147520884-b8070d29-b7c5-4bc5-ae8b-e885117a92d8.png)
Si proporciono un número negativo en la opción del volumen, tira Interacción Fallida

**Comment by Mateo-tem** [comment]
Bug Corregido. Los números negativos eran aceptados en el comando pero ahora le añadimos un filtro para evitar que eso pase. Gracias por reportar el error. Saludos.
