### ISSUE TITLE
Bug en el comando: timeout

### ISSUE THREAD

**Issue by polarsito** [Mateo-tem/COSM0#9]
![image](https://user-images.githubusercontent.com/91166604/147521196-6f6bb84e-52fb-4efb-8a0b-2aa75dd283d8.png)
Puedo usar el comando  con números negativos, responde como si hubiera lo hubiera aislado, pero no lo hace

**Comment by Mateo-tem** [comment]
Reparado. Los filtros del tiempo no estaban bien configurados. Gracias por reportar el error.
